services:
  backend:
    build: ./backend-agenda
    ports:
      - "5000:5000"
    volumes:
      - ./backend-agenda:/backend
    environment:
      - FLASK_ENV=development

#  frontend:
#    build: ./front-agenda
#    ports:
#      - "80:80"
#    depends_on:
#      - backend